### PR TITLE
Add .ga TLD server

### PR DESCRIPTION
**Pull request by proukornew**

### CODE REVIEW

**Comment by tranlam20220101** [comment]
Following the takeover of the management of .GA (official extension for Gabon) by ANINF (Agence Nationale des Infrastructures Numériques et des Fréquences), we would like to inform you that it is once again possible to register and transfer .GA domain names from 6 June (read the official press release on https://www.mon.ga/english.html). @proukornew

**Comment by proukornew** [comment]
> we would like to inform you that it is once again possible to register and transfer .GA domain names from 6 June
LOLWUT? Are u from afnic? There is no such info in press release.
I have already paid once for 10 years and will not pay again no more.
Also domains are not available for registration due to squatting by safenames.

**Comment by tranlam20220101** [comment]
@proukornew No bro. This is a notice from Netim Registrar

**Comment by tranlam20220101** [comment]
I just read it today. Unfortunately I'm slow too. @proukornew 
https://www.namepros.com/threads/ga-zone-now-under-nic-fr-not-freenom.1303763/

**Comment by proukornew** [comment]
https://lowendtalk.com/discussion/comment/3671390/#Comment_3671390

**Review by pemensik — APPROVED** [review]

**Comment by rfc1036** [comment]
Merged from a different source, thank you anyway for your contribution.

**Pull request closed without merging**
