### PR TITLE
Temporary whois.conf fix for ICANN's new gTLDs

### PR DESCRIPTION
**Pull request by ShadowOfHarbringer**
Hello.

Since whois is no longer working with all new gTLDs and seems there is no standardised way to deal with it, I propose adding these to whois.conf as a temporary solution.

### CODE REVIEW

**Comment by ShadowOfHarbringer** [comment]
I got them from here:

https://gist.github.com/thde/3890aa48e03a2b551374

**Comment by rfc1036** [comment]
Please clarify what you believe is no longer working.

**Comment by ShadowOfHarbringer** [comment]
I have stock whois built on Gentoo, version 5.2.12

When I run the following command:
`$ whois bcash.games`

Whois returns:
`No whois server is known for this kind of object.`

And with new whois.conf it gives:
`Domain Name: bcash.games
Registry Domain ID: 473ef000742b44e99cd4098a223b0bb3-RSIDE
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: https://www.namecheap.com/
Updated Date: 2017-12-24T08:10:30Z
Creation Date: 2017-10-08T08:10:42Z
Registry Expiry Date: 2023-10-08T08:10:42Z
Registrar: Namecheap, Inc.
Registrar IANA ID: 1068
Registrar Abuse Contact Email: abuse@namecheap.com
Registrar Abuse Contact Phone: +1.6613102107
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Registry Registrant ID: f9d0361dfecb4554af81dd8f2a8aa1ef-RSIDE
Registrant Name: WhoisGuard Protected
Registrant Organization: WhoisGuard, Inc.
Registrant Street: P.O. Box 0823-03411
Registrant City: Panama
Registrant State/Province: Panama
Registrant Postal Code: 
Registrant Country: PA
Registrant Phone: +507.8365503
Registrant Phone Ext: 
Registrant Fax: +51.17057182
Registrant Fax Ext: 
Registrant Email: ee33872029a64895abad2087411c62d0.protect@whoisguard.com
Registry Admin ID: 5c53320f351a4dae984fb95f65931b28-RSIDE`

**Comment by ShadowOfHarbringer** [comment]
Although the "no longer" is obviously wrong, it was probably never working with the new gTLDs. 

What I meant to say it is not working with new ICANN features, thus being **no longer** compatibile with World Wide Web.

**Comment by rfc1036** [comment]
Well, apparently you like jumping to conclusions. You just need to upgrade the program to a newer release: https://packages.gentoo.org/packages/net-misc/whois .

**Comment by ShadowOfHarbringer** [comment]
I didn't upgrade before because it was not marked as stable yet in Gentoo's repository.

Sorry, my fault then.

**Pull request closed without merging**
