### PR TITLE
Added target OS

### PR DESCRIPTION
**Pull request by Gitoffthelawn**

### CODE REVIEW

**Comment by rfc1036** [comment]
Your patch is both factually wrong and useless. Please do not waste people's time.

**Comment by Gitoffthelawn** [comment]
Wow. How rude and hurtful. Just trying to help others.

**Comment by udittmer** [comment]
Help others how? It's true that the patch didn't do anything useful, so what was its purpose?

**Comment by Gitoffthelawn** [comment]
When someone creates a repo, it is helpful to indicate on which platforms the software will run.  I was trying to be helpful by providing that information to others so each visitor wouldn't have to spend their limited time to try to figure it out.

All you had to do was edit my pull request (I specifically enabled that option) or create your own.  There was no need to be rude and hurtful.

**Comment by Keisial** [comment]
@Gitoffthelawn this client will work on almost any OS for which you compile it: Linux, Windows Mac, BSD…

**Pull request closed without merging**
