### PR TITLE
add Russian 3LDs

### PR DESCRIPTION
**Pull request by nextiny**
Hi all, I propose to add authoritative WHOIS servers of several Russian 3lvl domains. 

I found that .edu.ru is already on the list, but many others (much more popular) are not yet.

There are a lot of Russian 3LDs supported by Foundation for Assistance for Internet Technologies and Infrastructure Development (FAITID) and Moscow Internet Exchange (MSK-IX), not presented in the list at now.

Also there are .ac.ru (managed by N. D. Zelinsky Institute of Organic Chemistry (ZIOC) of the Russian Academy of Sciences since 1996, whois.free.net), .int.ru, mil.ru, gov.ru (have no known working whois services at the moment).

Historically they are working as "generic" (public) domains (excepting mil.ru and gov.ru).

FAITID uses "thin" registry model, MSK-IX and ZIOC use "thick". 

The most popular are org.ru, net.ru, pp.ru (MSK-IX), com.ru, msk.ru, spb.ru (FAITID).

Domain examples: itp.ac.ru, nokia.com.ru, echo.msk.ru, etc.  

About FAITID (in English): 
https://faitid.org/en/
http://flexireg.net/en
http://flexireg.net/en/stat_info (zone statistics)
http://flexireg.net/whois-terms_of_use.en.html (whois rules)
https://www.iana.org/domains/root/db/moscow.html (contact info in IANA root db)

About MSK-IX (in Russian):
http://net.ru/documents.html
https://nic.net.ru/whoispol.html
http://net.ru/stat/ (zone statistics)

About ZIOC:
http://ioc.ac.ru/english (in English), http://zioc.ru/ (in Russian) 
https://zioc.ru/science/nd-zelinsky-institute-of-organic-chemistry-of-russian-academy-of-science-today (in English)
http://www.free.net/EN/index.htm (FREEnet ZIOC academic network, in English)
http://www.free.net/ (in Russian)
http://www.free.net/Support/DNS/domain.ac.ru.htm (.ac.ru rules, in Russian)

UPD: Additionally, all they are on Mozilla Public Suffix List.

### CODE REVIEW

**Comment by rfc1036** [comment]
Thank you for the update. I do not think that I want to add more unofficial SLDs (e.g. *.net): can you upate the patch to only list the official domains?

**Comment by nextiny** [comment]
Hi, thank you for response. I updated the patch, now it includes the most popular domains only.

As a user, I think other zones should be added as well: some of them are popular enough, and all they are on Mozilla Public Suffix List (in particular, recognized by browsers and CAs). But it's just an opinion and probably it should be discussed separately.

**Comment by nextiny** [comment]
Hi! I updated the patch a while ago as you asked, but it's still awaiting your approval.

**Comment by rfc1036** [comment]
Merged in 5.5.7.

**Pull request closed without merging**
